# Generated by Django 5.0.7 on 2024-09-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField()),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
            ],
        ),
    ]
